name: Deploy Torrent Manager

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.lower.outputs.image_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Lowercase Registry Name
        id: lower
        run: |
          echo "image_name=ghcr.io/${{ github.repository_owner }}/docker-stopper" | tr '[:upper:]' '[:lower:]' >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push
        run: |
          docker build -t ${{ steps.lower.outputs.image_name }}:latest .
          docker push ${{ steps.lower.outputs.image_name }}:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull and Deploy
        run: |
          cd ~/media/docker-stopper
          docker pull ${{ needs.build-and-push.outputs.image_name }}:latest
          docker compose up -d
          # Optional: Clean up old images to save space
          docker image prune -f