name: Deploy Torrent Manager

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.lower.outputs.image_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Lowercase Registry Name
        id: lower
        run: |
          echo "image_name=ghcr.io/${{ github.repository_owner }}/docker-stopper" | tr '[:upper:]' '[:lower:]' >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push
        run: |
          docker build -t ${{ steps.lower.outputs.image_name }}:latest .
          docker push ${{ steps.lower.outputs.image_name }}:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      # 1. This brings your docker-compose.yml from GitHub to the server
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login so we can pull the private image
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 3. Pull and Deploy from the current workspace
      - name: Pull and Deploy
        run: |
          # No need to 'cd' if your compose file is in the root of your repo
          docker compose pull
          docker compose up -d
          docker image prune -f